apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-service-4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-web-service-4
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: "team=donkey stage=dev project=demo service=simple-web-service-4"
        - name: SERVICE_TO_CALL_URL
          value: http://simple-web-service-5:8580/api/message
        image: dtdemos/simple-web-service-4:0.1.0
        imagePullPolicy: "Always"
        name: simple-web-service-4
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
