apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-service-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-web-service-2
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: k8-simple-web-service-2
        - name: DT_CUSTOM_PROP
          value: "team=bat stage=dev project=demo service=simple-web-service-2"
        - name: SERVICE_TO_CALL_URL
          value: http://simple-web-service-3:8380/api/message
        image: dtdemos/simple-web-service-2:0.1.0
        imagePullPolicy: "Always"
        name: simple-web-service-2
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
