apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-service-5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-web-service-5
    spec:
      containers:
      - env:
        - name: SERVICE_NAME
          value: k8-simple-web-service-5
        - name: DT_CUSTOM_PROP
          value: "team=elephant stage=dev project=demo service=simple-web-service-5"
        - name: SERVICE_TO_CALL_URL
          value: none
        image: dtdemos/simple-web-service-5:0.1.0
        imagePullPolicy: "Always"
        name: simple-web-service-5
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
