apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-1
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: simple-web-app-1
  type: LoadBalancer
status:
  loadBalancer: {}