apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-1
spec:
  ports:
  - name: "8180"
    port: 8180
    targetPort: 8080
  selector:
    app: simple-web-service-1
  type: LoadBalancer
status:
  loadBalancer: {}
