apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-2
spec:
  ports:
  - name: "8280"
    port: 8280
    targetPort: 8080
  selector:
    app: simple-web-service-2
  type: LoadBalancer
status:
  loadBalancer: {}
