apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-3
spec:
  ports:
  - name: "8380"
    port: 8380
    targetPort: 8080
  selector:
    app: simple-web-service-3
  type: LoadBalancer
status:
  loadBalancer: {}
