apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-4
spec:
  ports:
  - name: "8480"
    port: 8480
    targetPort: 8080
  selector:
    app: simple-web-service-4
  type: LoadBalancer
status:
  loadBalancer: {}
