apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-5
spec:
  ports:
  - name: "8580"
    port: 8580
    targetPort: 8080
  selector:
    app: simple-web-service-5
  type: LoadBalancer
status:
  loadBalancer: {}
