apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-2
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8080
  selector:
    app: simple-web-app-2
  type: LoadBalancer
status:
  loadBalancer: {}