# simple-web-service-1 ################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service-1
  namespace: simple-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-service-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-web-service-1
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: "stage=dev project=demo service=simple-web-service-1"
        - name: SERVICE_TO_CALL_URL
          value: http://simple-web-service-2:8280/api/message
        image: dtdemos/simple-web-service-1:0.1.0
        imagePullPolicy: "Always"
        name: simple-web-service-1
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-1
  namespace: simple-dev
spec:
  ports:
  - name: "8180"
    port: 8180
    targetPort: 8080
  selector:
    app: simple-web-service-1
  type: LoadBalancer
status:
  loadBalancer: {}
---
# simple-web-service-2 ################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service-2
  namespace: simple-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-service-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-web-service-2
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: "stage=dev project=demo service=simple-web-service-2"
        - name: SERVICE_TO_CALL_URL
          value: http://simple-web-service-3:8380/api/message
        image: dtdemos/simple-web-service-2:0.1.0
        imagePullPolicy: "Always"
        name: simple-web-service-2
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-2
  namespace: simple-dev
spec:
  ports:
  - name: "8280"
    port: 8280
    targetPort: 8080
  selector:
    app: simple-web-service-2
  type: LoadBalancer
status:
  loadBalancer: {}
# simple-web-service-3 ################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-service-3
  namespace: simple-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-web-service-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-web-service-3
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: "stage=dev project=demo service=simple-web-service-3"
        - name: SERVICE_TO_CALL_URL
          value: none
        image: dtdemos/simple-web-service-3:0.1.0
        imagePullPolicy: "Always"
        name: simple-web-service-3
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service-3
  namespace: simple-dev
spec:
  ports:
  - name: "8380"
    port: 8380
    targetPort: 8080
  selector:
    app: simple-web-service-3
  type: LoadBalancer
status:
  loadBalancer: {}
